### ISSUE TITLE
Partitioning between multiple threads

### ISSUE THREAD

**Issue by chocological00** [paulgb/tiny_id#1]
Hi, I found your crate while searching for non-colliding short alphanumeric id generator, and it seems like this will fit very well for my purpose.

One problem is that I have several threads that will be generating ids concurrently and I cannot have collision between those threads.

To avoid collisions, I could make the generator as a global variable behind a lock, but I think this approach might be slow.

Cloning the incremented generator when each thread gets created, and skipping by the number of total threads every generation sounds like a better approach, but I was wondering if you would be willing to implement this natively (as mentioned in README.md).

**Comment by paulgb** [comment]
Hi @chocological00,

I've implemented the partitioning approach I had in mind. It's now briefly [documented in the readme](https://github.com/paulgb/tiny_id#partitioning) as well. Please let me know if you have any questions, since if you do I'm sure others will too!

The version with partitioning is 0.1.4 on crates.
